config/routes.rb
require 'sidekiq/web'

require_dependency 'admin_constraint'

# This used to be User#username_format, but that causes a preload of the User object
# and makes Guard not work properly.
USERNAME_ROUTE_FORMAT = /[A-Za-z0-9\_]+/

Discourse::Application.routes.draw do

  match "/404", :to => "exceptions#not_found"

  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  resources :forums do
    collection do
      get 'request_access'
      post 'request_access_submit'
    end
  end
  get 'srv/status' => 'forums#status'

  namespace :admin, constraints: AdminConstraint.new do
    get '' => 'admin#index'

    resources :site_settings
    get 'reports/:type' => 'reports#show'

    resources :users, id: USERNAME_ROUTE_FORMAT do
      collection do
        get 'list/:query' => 'users#index'
        put 'approve-bulk' => 'users#approve_bulk'
      end
      put 'ban'
      put 'delete_all_posts'
      put 'unban'
      put 'revoke_admin'
      put 'grant_admin'
      put 'revoke_moderation'
      put 'grant_moderation'
      put 'approve'
      post 'refresh_browsers'
    end

    resources :impersonate
    resources :email_logs do
      collection do
        post 'test'
      end
    end
    get 'customize' => 'site_customizations#index'
    get 'flags' => 'flags#index'
    get 'flags/:filter' => 'flags#index'
    post 'flags/clear/:id' => 'flags#clear'
    resources :site_customizations
    resources :export
    get 'version_check' => 'versions#show'
    resources :dashboard, only: [:index]
  end

  get 'email_preferences' => 'email#preferences_redirect'
  get 'email/unsubscribe/:key' => 'email#unsubscribe', as: 'email_unsubscribe'
  post 'email/resubscribe/:key' => 'email#resubscribe', as: 'email_resubscribe'


  resources :session, id: USERNAME_ROUTE_FORMAT, :only => [:create, :destroy] do
    collection do
      post 'forgot_password'
    end
  end

  resources :users, :except => [:show, :update] do
    collection do
      get 'check_username'
      get 'is_local_username'
    end
  end

  resources :static
  post 'login' => 'static#enter'
  get 'faq' => 'static#show', id: 'faq'
  get 'tos' => 'static#show', id: 'tos'
  get 'privacy' => 'static#show', id: 'privacy'

  get 'users/search/users' => 'users#search_users'
  get 'users/password-reset/:token' => 'users#password_reset'
  put 'users/password-reset/:token' => 'users#password_reset'
  get 'users/activate-account/:token' => 'users#activate_account'
  get 'users/authorize-email/:token' => 'users#authorize_email'
  get 'users/hp' => 'users#get_honeypot_value'

  get 'user_preferences' => 'users#user_preferences_redirect'
  get 'users/:username/private-messages' => 'user_actions#private_messages', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  get 'users/:username' => 'users#show', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  put 'users/:username' => 'users#update', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  get 'users/:username/preferences' => 'users#preferences', :constraints => {:username => USERNAME_ROUTE_FORMAT}, :as => :email_preferences
  get 'users/:username/preferences/email' => 'users#preferences', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  put 'users/:username/preferences/email' => 'users#change_email', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  get 'users/:username/preferences/username' => 'users#preferences', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  put 'users/:username/preferences/username' => 'users#username', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  get 'users/:username/avatar(/:size)' => 'users#avatar', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  get 'users/:username/invited' => 'users#invited', :constraints => {:username => USERNAME_ROUTE_FORMAT}
  get 'users/:username/send_activation_email' => 'users#send_activation_email', :constraints => {:username => USERNAME_ROUTE_FORMAT}

  resources :uploads


  get 'posts/by_number/:topic_id/:post_number' => 'posts#by_number'
  resources :posts do
    get 'versions'
    put 'bookmark'
    get 'replies'
    put 'recover'
    collection do
      delete 'destroy_many'
    end
  end

  resources :notifications
  resources :categories

  match "/auth/:provider/callback", to: "users/omniauth_callbacks#complete"
  match "/auth/failure", to: "users/omniauth_callbacks#failure"

  resources :clicks do
    collection do
      get 'track'
    end
  end

  get 'excerpt' => 'excerpt#show'

  resources :post_actions do
    collection do
      get 'users'
      post 'clear_flags'
    end
  end
  resources :user_actions
  resources :education

  get 'category/:category.rss' => 'list#category_feed', format: :rss, as: 'category_feed'
  get 'category/:category' => 'list#category'
  get 'category/:category' => 'list#category', as: 'category'
  get 'category/:category/more' => 'list#category', as: 'category'
  get 'categories' => 'categories#index'
  get 'popular' => 'list#index'
  get 'popular/more' => 'list#index'
  get 'favorited' => 'list#favorited'
  get 'favorited/more' => 'list#favorited'
  get 'read' => 'list#read'
  get 'read/more' => 'list#read'
  get 'unread' => 'list#unread'
  get 'unread/more' => 'list#unread'
  get 'new' => 'list#new'
  get 'new/more' => 'list#new'
  get 'posted' => 'list#posted'
  get 'posted/more' => 'list#posted'

  get 'search' => 'search#query'

  # Topics resource
  get 't/:id' => 'topics#show'
  delete 't/:id' => 'topics#destroy'
  put 't/:id' => 'topics#update'
  post 't' => 'topics#create'
  post 'topics/timings'
  get 'topics/similar_to'

  # Legacy route for old avatars
  get 'threads/:topic_id/:post_number/avatar' => 'topics#avatar', :constraints => {:topic_id => /\d+/, :post_number => /\d+/}

  # Topic routes
  get 't/:slug/:topic_id/best_of' => 'topics#show', :defaults => {best_of: true}, :constraints => {:topic_id => /\d+/, :post_number => /\d+/}
  get 't/:topic_id/best_of' => 'topics#show', :constraints => {:topic_id => /\d+/, :post_number => /\d+/}
  put 't/:slug/:topic_id' => 'topics#update', :constraints => {:topic_id => /\d+/}
  put 't/:slug/:topic_id/star' => 'topics#star', :constraints => {:topic_id => /\d+/}
  put 't/:topic_id/star' => 'topics#star', :constraints => {:topic_id => /\d+/}
  put 't/:slug/:topic_id/status' => 'topics#status', :constraints => {:topic_id => /\d+/}
  put 't/:topic_id/status' => 'topics#status', :constraints => {:topic_id => /\d+/}
  put 't/:topic_id/clear-pin' => 'topics#clear_pin', :constraints => {:topic_id => /\d+/}
  put 't/:topic_id/mute' => 'topics#mute', :constraints => {:topic_id => /\d+/}
  put 't/:topic_id/unmute' => 'topics#unmute', :constraints => {:topic_id => /\d+/}

  get 't/:topic_id/:post_number' => 'topics#show', :constraints => {:topic_id => /\d+/, :post_number => /\d+/}
  get 't/:slug/:topic_id.rss' => 'topics#feed', :format => :rss, :constraints => {:topic_id => /\d+/}
  get 't/:slug/:topic_id' => 'topics#show', :constraints => {:topic_id => /\d+/}
  get 't/:slug/:topic_id/:post_number' => 'topics#show', :constraints => {:topic_id => /\d+/, :post_number => /\d+/}
  post 't/:topic_id/timings' => 'topics#timings', :constraints => {:topic_id => /\d+/}
  post 't/:topic_id/invite' => 'topics#invite', :constraints => {:topic_id => /\d+/}
  post 't/:topic_id/move-posts' => 'topics#move_posts', :constraints => {:topic_id => /\d+/}
  delete 't/:topic_id/timings' => 'topics#destroy_timings', :constraints => {:topic_id => /\d+/}

  post 't/:topic_id/notifications' => 'topics#set_notifications' , :constraints => {:topic_id => /\d+/}


  resources :invites
  delete 'invites' => 'invites#destroy'

  get 'request_access' => 'request_access#new'
  post 'request_access' => 'request_access#create'

  get 'onebox' => 'onebox#show'

  get 'error' => 'forums#error'

  get 'message-bus/poll' => 'message_bus#poll'

  get 'draft' => 'draft#show'
  post 'draft' => 'draft#update'
  delete 'draft' => 'draft#destroy'


  get 'robots.txt' => 'robots_txt#index'

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root to: 'list#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) + ' - ' + t(:title) : t(:title) %></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">

    <%= canonical_link_tag %>

    <link rel="icon" type="image/png" href=<%=SiteSetting.favicon_url%>>
    <%= javascript_include_tag "preload_store" %>

    <%= render :partial => "common/special_font_face" %>
    <%= render :partial => "common/discourse_stylesheet" %>

    <%= csrf_meta_tags %>

    <%= yield :head %>
  </head>

  <body>
    <% unless current_user %>
      <form id='hidden-login-form' method="post" action="<%=login_path%>" style="display: none;">
        <input name="username" type="text"     id="signin_username">
        <input name="password" type="password" id="signin_password">
        <input name="redirect" type="hidden">
        <input name="authenticity_token" type="hidden" />
        <input type="submit" id="signin-button" value="Log In">
      </form>
    <% end %>

    <%=SiteCustomization.custom_header(session[:preview_style])%>
    <section id='main'>
      <section id='loading-message' style='display:none'><%= t :loading %>...</section>
      <noscript data-path="<%= request.env['PATH_INFO'] %>">
        <header class="d-header">
          <div class="container">
            <div class="contents">
              <div class="row">
                <div class="title span13">
                  <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
                </div>
              </div>
            </div>
          </div>
        </header>
        <div id="main-outlet" class="container">
          <!-- preload-content: -->
          <%= yield %>
          <!-- :preload-content -->
        </div>
      </noscript>
    </section>

    <%- if @preloaded.present? %>
      <script>
      <%- @preloaded.each do |key, json| %>
        PreloadStore.store("<%= key %>", <%= raw json %>)
      <% end %>
      </script>
    <%- end %>

    <%= yield :data %>

    <footer id='bottom'></footer>

    <%= render :partial => "common/discourse_javascript" %>
    <%= render :partial => "common/persona_javascript" if SiteSetting.enable_persona_logins %>
    <%= render_google_analytics_code %>

    <!-- Discourse Version: <%= Discourse::VERSION::STRING %> -->
    <!-- Git Version: <%= Discourse.git_version %> -->
  </body>
</html>

app/views/layouts/no_js.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%=t :title%></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <link rel="icon" type="image/png" href=<%=SiteSetting.favicon_url%>>

    <%- if mini_profiler_enabled? %>
      <%- Rack::MiniProfiler.step "stylsheet" do%>
        <%=stylesheet_link_tag "application"%>
      <%- end %>
      <%- if current_user.try(:admin) %>
        <%- Rack::MiniProfiler.step "stylsheet" do%>
          <%= stylesheet_link_tag "admin"%>
        <%-end%>
      <%- end %>

    <%- else %>
      <%=stylesheet_link_tag "application"%>
      <%- if current_user.try(:admin) %>
        <%= stylesheet_link_tag "admin"%>
      <%- end %>
    <%- end %>

    <%=csrf_meta_tags%>
  </head>

  <body>

    <section id='main'>
    <header class="d-header">
      <div class="container">
        <div class="contents">
          <div class="row">
            <div class="title span13">
              <a href="/"><img src="<%=SiteSetting.logo_url%>" alt="<%=SiteSetting.title%>" id="site-logo"></a>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div id="main-outlet" class="container">
      <%= yield %>
    </div>
    </section>

    <footer id='bottom'>
    </footer>
  </body>
</html>